// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {swim} from '../models';

export function GetClusterNodes():Promise<Array<swim.Node>>;

export function Greet(arg1:string):Promise<string>;

export function KillNode():Promise<void>;

export function ScanForNodes():Promise<void>;
