// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClusterNodes() {
  return window['go']['main']['App']['GetClusterNodes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function KillNode() {
  return window['go']['main']['App']['KillNode']();
}

export function ScanForNodes() {
  return window['go']['main']['App']['ScanForNodes']();
}
