// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {swim} from '../models';
import {master} from '../models';

export function GetClusterNodes():Promise<Array<swim.Node>>;

export function GetCompletedJobs():Promise<Array<master.CompletedJob>>;

export function GetQueueDepth():Promise<number>;

export function KillNode():Promise<void>;

export function ScanForNodes():Promise<void>;

export function UploadDocument():Promise<number>;
